name: FsWarn Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/library/alpine:edge

    steps:
      - uses: actions/checkout@v4

      - name: Generate rootfs
        run: |
          apk add xz squashfs-tools
          /bin/sh ./genrootfs.sh
          ARCH=aarch64 /bin/sh ./genrootfs.sh

      - uses: actions/upload-artifact@v4
        with:
          name: FsWarn
          path: ./fswarn*.squash
