name: FsWarn Build

on:
  push:
    tags:
      - 'v*'


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/library/alpine:edge

    steps:
      - uses: actions/checkout@v4

      - name: Generate rootfs
        run: |
          apk add xz squashfs-tools
          /bin/sh ./genrootfs.sh
          tar cvf fswarn.tar.xz fswarn-x86_64.squash

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: fswarn.tar.xz
